### ISSUE TITLE
The Chinese interface font is too large, which makes it look crowded.

### ISSUE THREAD

**Issue by Leroy-X** [TimerTiTi/TiTi_Android#183]
English:
![11207149da31f49bef98d39a2484b13](https://github.com/user-attachments/assets/89517f9c-ed96-4899-befe-4c623a620bec)

Chinese:
![5a544b0644cf84205ea1f1cd55c1218](https://github.com/user-attachments/assets/8453096a-7e48-4754-9ecf-f972f7db2ca1)

In the Chinese interface, the numbers in the timer are zero-spaced, for example, the number zero will be connected together.

Byw, In addition, in the English interface, the task names in Chinese cannot be displayed. I think this may be limited by the font.

**Comment by koreatlwls** [comment]
Thank you for your interest in our TimerTiTi project.
As you correctly pointed out in your response, the English font indeed does not support Chinese characters, resulting in the Chinese text not being displayed properly.
Additionally, we've become aware of the zero-width space problem when using Chinese fonts.
I will promptly discuss these font-related concerns with the team to resolve these issues as quickly as possible.

**Comment by koreatlwls** [comment]
@Leroy-X
It will be revised to version 1.4.1
Thanks
